blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¥ Bug Report"
    url: https://github.com/vikejs/vike/issues/new/choose
    about: "Report bugs at Vike's main repository instead."
  - name: "âœ¨ Feature Request"
    url: https://github.com/vikejs/vike/issues/new/choose
    about: "Suggest features at Vike's main repository instead."
  - name: "ğŸ™ Help & Questions"
    url: https://github.com/vikejs/vike/discussions/new?category=help-questions
    about: "Get official help from Vike maintainers."
  - name: "ğŸ—¨ï¸ Other"
    url: https://github.com/vikejs/vike/discussions/new?category=other
    about: "Anything else: ideas, feedback, complaints, appreciation, ..."
  - name: "ğŸ’¬ Chit-chat"
    url: https://discord.com/invite/hfHhnJyVg8
    about: "Casual conversation with the community."
